### ISSUE TITLE
Error while opening preferences

### ISSUE THREAD

**Issue by mohinderq** [ShadyThGod/altus#1]
On my Macbook Air I got the following error, after opening preferences:

Uncaught Exception:
Error: Object has been destroyed
    at createPrefWindow (/Applications/Altus.app/Contents/Resources/app.asar/main.js:241:20)
    at click (/Applications/Altus.app/Contents/Resources/app.asar/main.js:303:13)
    at MenuItem.click (/Applications/Altus.app/Contents/Resources/electron.asar/browser/api/menu-item.js:55:9)
    at Function.executeCommand (/Applications/Altus.app/Contents/Resources/electron.asar/browser/api/menu.js:29:13)

**Comment by ShadyThGod** [comment]
Must be fixed now. If you are building it on your own, you can go ahead or wait for the proper release which will get done by tomorrow. Let me know if it is fixed for you or not.

**Comment by ShadyThGod** [comment]
[Release v1.1.1](https://github.com/ShadyThGod/altus/releases/tag/1.1.1) has the fix.
